"""initial schema

Revision ID: 9e77641c00a3
Revises: 
Created: 2026-08-20 20:41:57.485916
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9e77641c00a3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.Enum('login', 'login_failed', 'logout', 'user_registered', 'password_changed', 'license_activated', 'license_deactivated', 'exchange_account_connected', 'exchange_account_removed', 'strategy_created', 'strategy_updated', 'risk_config_changed', 'bot_started', 'bot_stopped', 'live_trading_activated', 'order_placed', 'order_cancelled', 'emergency_stop', 'kill_switch_reset', name='audit_action', native_enum=False, length=48), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_audit_user_time', ['user_id', 'occurred_at'], unique=False)

    op.create_table('instruments',
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('base_asset', sa.String(length=16), nullable=False),
    sa.Column('quote_asset', sa.String(length=16), nullable=False),
    sa.Column('instrument_type', sa.Enum('spot', 'linear_perpetual', 'inverse_perpetual', 'futures', name='instrument_type', native_enum=False, length=48), nullable=False),
    sa.Column('tick_size', sa.Float(), nullable=False),
    sa.Column('lot_size', sa.Float(), nullable=False),
    sa.Column('min_quantity', sa.Float(), nullable=False),
    sa.Column('min_notional', sa.Float(), nullable=False),
    sa.Column('max_leverage', sa.Float(), nullable=False),
    sa.Column('maker_fee', sa.Float(), nullable=False),
    sa.Column('taker_fee', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments')),
    sa.UniqueConstraint('exchange', 'symbol', name='uq_instrument')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_created_at'), ['created_at'], unique=False)

    op.create_table('market_candles',
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.CheckConstraint('high >= low', name=op.f('ck_market_candles_high_ge_low')),
    sa.PrimaryKeyConstraint('exchange', 'symbol', 'interval', 'open_time', name=op.f('pk_market_candles'))
    )
    with op.batch_alter_table('market_candles', schema=None) as batch_op:
        batch_op.create_index('ix_candles_lookup', ['exchange', 'symbol', 'interval', 'open_time'], unique=False)

    op.create_table('market_regimes',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('regime', sa.Enum('trending_bull', 'trending_bear', 'ranging', 'high_volatility', 'low_volatility', 'unknown', name='market_regime', native_enum=False, length=48), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('adx', sa.Float(), nullable=True),
    sa.Column('atr_pct', sa.Float(), nullable=True),
    sa.Column('trend_slope', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_regimes'))
    )
    with op.batch_alter_table('market_regimes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_regimes_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_regimes_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_regimes_symbol_time', ['symbol', 'interval', 'detected_at'], unique=False)

    op.create_table('market_ticks',
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('bid_size', sa.Float(), nullable=True),
    sa.Column('ask_size', sa.Float(), nullable=True),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.Column('funding_rate', sa.Float(), nullable=True),
    sa.Column('open_interest', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_ticks'))
    )
    with op.batch_alter_table('market_ticks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_ticks_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_ticks_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_ticks_symbol_time', ['symbol', 'timestamp'], unique=False)

    op.create_table('news_articles',
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_reputation', sa.Float(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of', sa.String(length=36), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_articles')),
    sa.UniqueConstraint('content_hash', name='uq_news_content_hash')
    )
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_articles_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_duplicate_of'), ['duplicate_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_source'), ['source'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('pending_verification', 'active', 'suspended', 'deleted', name='user_status', native_enum=False, length=48), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email_verification_token'), ['email_verification_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_password_reset_token'), ['password_reset_token'], unique=False)

    op.create_table('exchange_accounts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('is_testnet', sa.Boolean(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('api_key_masked', sa.String(length=64), nullable=True),
    sa.Column('api_key_fingerprint', sa.String(length=32), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('can_withdraw', sa.Boolean(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exchange_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange_accounts')),
    sa.UniqueConstraint('user_id', 'name', name='uq_exchange_account_name')
    )
    with op.batch_alter_table('exchange_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_accounts_api_key_fingerprint'), ['api_key_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchange_accounts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchange_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('licenses',
    sa.Column('license_key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.Enum('trial', 'starter', 'pro', 'enterprise', name='license_plan', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('inactive', 'active', 'expired', 'suspended', 'revoked', name='license_status', native_enum=False, length=48), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_limit', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('device_limit >= 1', name=op.f('ck_licenses_device_limit_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_licenses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licenses'))
    )
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_licenses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_licenses_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_licenses_license_key'), ['license_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_licenses_user_id'), ['user_id'], unique=False)

    op.create_table('news_analyses',
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.Enum('regulation', 'etf', 'macro', 'interest_rates', 'inflation', 'earnings', 'exchange_incident', 'hack', 'token_unlock', 'partnership', 'acquisition', 'leadership_change', 'legal', 'geopolitical', 'other', name='news_event_type', native_enum=False, length=48), nullable=False),
    sa.Column('sentiment', sa.Enum('very_negative', 'negative', 'neutral', 'positive', 'very_positive', name='news_sentiment', native_enum=False, length=48), nullable=False),
    sa.Column('impact', sa.Enum('none', 'low', 'medium', 'high', 'critical', name='news_impact', native_enum=False, length=48), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('novelty', sa.Float(), nullable=False),
    sa.Column('urgency', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], name=op.f('fk_news_analyses_article_id_news_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_analyses')),
    sa.UniqueConstraint('article_id', 'asset', name='uq_news_analysis_asset')
    )
    with op.batch_alter_table('news_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_analyses_analyzed_at'), ['analyzed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_analyses_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_analyses_asset'), ['asset'], unique=False)

    op.create_table('portfolios',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('quote_currency', sa.String(length=16), nullable=False),
    sa.Column('trading_mode', sa.String(length=16), nullable=False),
    sa.Column('starting_balance', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('peak_equity', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('fees_paid', sa.Float(), nullable=False),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciliation_ok', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolios_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios'))
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('strategies',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('strategy_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('current_version', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_strategies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies')),
    sa.UniqueConstraint('user_id', 'name', name='uq_strategy_name')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategies_strategy_type'), ['strategy_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategies_user_id'), ['user_id'], unique=False)

    op.create_table('backtests',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('strategy_type', sa.String(length=64), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('risk_config', sa.JSON(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='backtest_status', native_enum=False, length=48), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('equity_curve', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_backtests_strategy_id_strategies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_backtests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtests'))
    )
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtests_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtests_user_id'), ['user_id'], unique=False)

    op.create_table('license_devices',
    sa.Column('license_id', sa.String(length=36), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], name=op.f('fk_license_devices_license_id_licenses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_license_devices')),
    sa.UniqueConstraint('license_id', 'device_fingerprint', name='uq_license_device')
    )
    with op.batch_alter_table('license_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_license_devices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_license_devices_device_fingerprint'), ['device_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_license_devices_license_id'), ['license_id'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('total_exposure', sa.Float(), nullable=False),
    sa.Column('position_count', sa.Integer(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_snapshots_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots'))
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_snapshots_pf_time', ['portfolio_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('strategy_versions',
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_strategy_versions_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_versions')),
    sa.UniqueConstraint('strategy_id', 'version', name='uq_strategy_version')
    )
    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_versions_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('license_id', sa.String(length=36), nullable=True),
    sa.Column('plan', sa.Enum('trial', 'starter', 'pro', 'enterprise', name='subscription_plan', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('trialing', 'active', 'past_due', 'cancelled', 'expired', name='subscription_status', native_enum=False, length=48), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=128), nullable=True),
    sa.Column('external_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], name=op.f('fk_subscriptions_license_id_licenses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_current_period_end'), ['current_period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_external_customer_id'), ['external_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_external_subscription_id'), ['external_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_license_id'), ['license_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('bots',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_version_id', sa.String(length=36), nullable=True),
    sa.Column('exchange_account_id', sa.String(length=36), nullable=True),
    sa.Column('portfolio_id', sa.String(length=36), nullable=True),
    sa.Column('trading_mode', sa.String(length=16), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('created', 'starting', 'running', 'paused', 'stopping', 'stopped', 'error', 'halted', name='bot_status', native_enum=False, length=48), nullable=False),
    sa.Column('risk_config', sa.JSON(), nullable=False),
    sa.Column('kill_switch_active', sa.Boolean(), nullable=False),
    sa.Column('kill_switch_reason', sa.Enum('manual', 'daily_loss', 'weekly_loss', 'max_drawdown', 'state_corruption', 'exchange_desync', 'stale_market_data', 'api_failures', 'abnormal_volatility', 'clock_drift', 'license_invalid', name='kill_switch_reason', native_enum=False, length=48), nullable=True),
    sa.Column('kill_switch_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['exchange_accounts.id'], name=op.f('fk_bots_exchange_account_id_exchange_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_bots_portfolio_id_portfolios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_bots_strategy_id_strategies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_bots_strategy_version_id_strategy_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bots')),
    sa.UniqueConstraint('user_id', 'name', name='uq_bot_name')
    )
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bots_exchange_account_id'), ['exchange_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bots_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bots_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bots_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bots_user_id'), ['user_id'], unique=False)

    op.create_table('bot_events',
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('started', 'stopped', 'paused', 'resumed', 'emergency_stop', 'signal_generated', 'order_submitted', 'order_filled', 'order_rejected', 'position_opened', 'position_closed', 'risk_blocked', 'kill_switch_tripped', 'reconciliation_mismatch', 'error', 'heartbeat', name='bot_event_type', native_enum=False, length=48), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_bot_events_bot_id_bots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_events'))
    )
    with op.batch_alter_table('bot_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_events_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index('ix_bot_events_bot_time', ['bot_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_events_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=True),
    sa.Column('event', sa.Enum('account_security', 'trade_opened', 'trade_closed', 'take_profit_hit', 'stop_loss_hit', 'risk_alert', 'daily_loss_limit', 'bot_crashed', 'exchange_disconnected', 'license_expiring', 'system_error', name='notification_event', native_enum=False, length=48), nullable=False),
    sa.Column('channel', sa.Enum('email', 'telegram', 'discord', 'web_push', 'in_app', name='notification_channel', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'suppressed', name='notification_status', native_enum=False, length=48), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_notifications_bot_id_bots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('orders',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=True),
    sa.Column('portfolio_id', sa.String(length=36), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=64), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='order_side', native_enum=False, length=48), nullable=False),
    sa.Column('order_type', sa.Enum('market', 'limit', 'stop_market', 'stop_limit', 'take_profit_market', 'take_profit_limit', 'trailing_stop', name='order_type', native_enum=False, length=48), nullable=False),
    sa.Column('time_in_force', sa.Enum('gtc', 'ioc', 'fok', 'post_only', name='time_in_force', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('pending', 'submitted', 'open', 'partially_filled', 'filled', 'cancelled', 'rejected', 'expired', 'unknown', name='order_status', native_enum=False, length=48), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('trigger_price', sa.Float(), nullable=True),
    sa.Column('filled_quantity', sa.Float(), nullable=False),
    sa.Column('average_fill_price', sa.Float(), nullable=False),
    sa.Column('fees_paid', sa.Float(), nullable=False),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_orders_quantity_positive')),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_orders_bot_id_bots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_orders_portfolio_id_portfolios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('user_id', 'client_order_id', name='uq_order_client_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_client_order_id'), ['client_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_exchange_order_id'), ['exchange_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_orders_user_symbol_status', ['user_id', 'symbol', 'status'], unique=False)

    op.create_table('positions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=True),
    sa.Column('portfolio_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('long', 'short', 'flat', name='position_side', native_enum=False, length=48), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('mark_price', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('trailing_stop', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('fees_paid', sa.Float(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strategy_name', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_positions_quantity_non_negative')),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_positions_bot_id_bots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_positions_portfolio_id_portfolios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_positions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_is_open'), ['is_open'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_positions_user_open', ['user_id', 'is_open'], unique=False)

    op.create_table('risk_events',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.Enum('limit_breach', 'daily_loss_limit', 'weekly_loss_limit', 'max_drawdown', 'exposure_limit', 'position_limit', 'leverage_limit', 'loss_streak', 'cooldown', 'liquidity', 'spread', 'slippage', 'stale_data', 'clock_drift', 'reconciliation', 'kill_switch', 'sizing_failed', 'trade_count_limit', name='risk_event_type', native_enum=False, length=48), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='risk_severity', native_enum=False, length=48), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('limit_value', sa.Float(), nullable=True),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('action_taken', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_risk_events_bot_id_bots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_risk_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_events'))
    )
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_events_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_user_id'), ['user_id'], unique=False)

    op.create_table('signals',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('action', sa.Enum('buy', 'sell', 'close', 'hold', 'no_trade', name='signal_action', native_enum=False, length=48), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('regime', sa.Enum('trending_bull', 'trending_bear', 'ranging', 'high_volatility', 'low_volatility', 'unknown', name='signal_regime', native_enum=False, length=48), nullable=True),
    sa.Column('news_score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('blocked_by', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_signals_bot_id_bots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_signals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_user_id'), ['user_id'], unique=False)

    op.create_table('trades',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=True),
    sa.Column('portfolio_id', sa.String(length=36), nullable=True),
    sa.Column('backtest_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('long', 'short', 'flat', name='trade_side', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='trade_status', native_enum=False, length=48), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gross_pnl', sa.Float(), nullable=False),
    sa.Column('net_pnl', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('slippage_cost', sa.Float(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.Enum('take_profit', 'stop_loss', 'trailing_stop', 'signal', 'manual', 'risk', 'kill_switch', 'end_of_backtest', 'liquidation', name='exit_reason', native_enum=False, length=48), nullable=True),
    sa.Column('strategy_name', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], name=op.f('fk_trades_backtest_id_backtests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_trades_bot_id_bots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_trades_portfolio_id_portfolios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trades_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_backtest_id'), ['backtest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_entry_time'), ['entry_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_exit_time'), ['exit_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_strategy_name'), ['strategy_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_trades_user_exit_time', ['user_id', 'exit_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_user_id'), ['user_id'], unique=False)

    op.create_table('order_fills',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('exchange_fill_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='fill_side', native_enum=False, length=48), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('fee_asset', sa.String(length=16), nullable=False),
    sa.Column('role', sa.Enum('maker', 'taker', name='liquidity_role', native_enum=False, length=48), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_fills_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_fills'))
    )
    with op.batch_alter_table('order_fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_fills_exchange_fill_id'), ['exchange_fill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_fills_filled_at'), ['filled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_fills_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_fills_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_fills_user_id'))
        batch_op.drop_index(batch_op.f('ix_order_fills_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_fills_filled_at'))
        batch_op.drop_index(batch_op.f('ix_order_fills_exchange_fill_id'))

    op.drop_table('order_fills')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_user_id'))
        batch_op.drop_index('ix_trades_user_exit_time')
        batch_op.drop_index(batch_op.f('ix_trades_symbol'))
        batch_op.drop_index(batch_op.f('ix_trades_strategy_name'))
        batch_op.drop_index(batch_op.f('ix_trades_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_trades_exit_time'))
        batch_op.drop_index(batch_op.f('ix_trades_entry_time'))
        batch_op.drop_index(batch_op.f('ix_trades_created_at'))
        batch_op.drop_index(batch_op.f('ix_trades_bot_id'))
        batch_op.drop_index(batch_op.f('ix_trades_backtest_id'))

    op.drop_table('trades')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_user_id'))
        batch_op.drop_index(batch_op.f('ix_signals_symbol'))
        batch_op.drop_index(batch_op.f('ix_signals_generated_at'))
        batch_op.drop_index(batch_op.f('ix_signals_bot_id'))
        batch_op.drop_index(batch_op.f('ix_signals_action'))

    op.drop_table('signals')
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_risk_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_risk_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_risk_events_bot_id'))

    op.drop_table('risk_events')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('ix_positions_user_open')
        batch_op.drop_index(batch_op.f('ix_positions_user_id'))
        batch_op.drop_index(batch_op.f('ix_positions_symbol'))
        batch_op.drop_index(batch_op.f('ix_positions_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_positions_is_open'))
        batch_op.drop_index(batch_op.f('ix_positions_created_at'))
        batch_op.drop_index(batch_op.f('ix_positions_bot_id'))

    op.drop_table('positions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_user_symbol_status')
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_symbol'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_orders_exchange_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))
        batch_op.drop_index(batch_op.f('ix_orders_client_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_bot_id'))

    op.drop_table('orders')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_event'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_bot_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('bot_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_bot_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_bot_events_event_type'))
        batch_op.drop_index('ix_bot_events_bot_time')
        batch_op.drop_index(batch_op.f('ix_bot_events_bot_id'))

    op.drop_table('bot_events')
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bots_user_id'))
        batch_op.drop_index(batch_op.f('ix_bots_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_bots_status'))
        batch_op.drop_index(batch_op.f('ix_bots_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_bots_exchange_account_id'))
        batch_op.drop_index(batch_op.f('ix_bots_created_at'))

    op.drop_table('bots')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_license_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_external_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_external_customer_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_current_period_end'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_created_at'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_versions_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_versions_created_at'))

    op.drop_table('strategy_versions')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_timestamp'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_portfolio_id'))
        batch_op.drop_index('ix_portfolio_snapshots_pf_time')

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('license_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_license_devices_license_id'))
        batch_op.drop_index(batch_op.f('ix_license_devices_device_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_license_devices_created_at'))

    op.drop_table('license_devices')
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtests_user_id'))
        batch_op.drop_index(batch_op.f('ix_backtests_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_backtests_status'))
        batch_op.drop_index(batch_op.f('ix_backtests_created_at'))

    op.drop_table('backtests')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategies_strategy_type'))
        batch_op.drop_index(batch_op.f('ix_strategies_created_at'))

    op.drop_table('strategies')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_created_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolios_created_at'))

    op.drop_table('portfolios')
    with op.batch_alter_table('news_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_analyses_asset'))
        batch_op.drop_index(batch_op.f('ix_news_analyses_article_id'))
        batch_op.drop_index(batch_op.f('ix_news_analyses_analyzed_at'))

    op.drop_table('news_analyses')
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licenses_user_id'))
        batch_op.drop_index(batch_op.f('ix_licenses_license_key'))
        batch_op.drop_index(batch_op.f('ix_licenses_expires_at'))
        batch_op.drop_index(batch_op.f('ix_licenses_created_at'))

    op.drop_table('licenses')
    with op.batch_alter_table('exchange_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_exchange_accounts_created_at'))
        batch_op.drop_index(batch_op.f('ix_exchange_accounts_api_key_fingerprint'))

    op.drop_table('exchange_accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_password_reset_token'))
        batch_op.drop_index(batch_op.f('ix_users_email_verification_token'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_articles_source'))
        batch_op.drop_index(batch_op.f('ix_news_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_articles_external_id'))
        batch_op.drop_index(batch_op.f('ix_news_articles_duplicate_of'))
        batch_op.drop_index(batch_op.f('ix_news_articles_content_hash'))

    op.drop_table('news_articles')
    with op.batch_alter_table('market_ticks', schema=None) as batch_op:
        batch_op.drop_index('ix_ticks_symbol_time')
        batch_op.drop_index(batch_op.f('ix_market_ticks_timestamp'))
        batch_op.drop_index(batch_op.f('ix_market_ticks_symbol'))

    op.drop_table('market_ticks')
    with op.batch_alter_table('market_regimes', schema=None) as batch_op:
        batch_op.drop_index('ix_regimes_symbol_time')
        batch_op.drop_index(batch_op.f('ix_market_regimes_symbol'))
        batch_op.drop_index(batch_op.f('ix_market_regimes_detected_at'))

    op.drop_table('market_regimes')
    with op.batch_alter_table('market_candles', schema=None) as batch_op:
        batch_op.drop_index('ix_candles_lookup')

    op.drop_table('market_candles')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_created_at'))

    op.drop_table('instruments')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_time')
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
